ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS seller_type ENUM('admin', 'vendor') NOT NULL DEFAULT 'admin' AFTER vendor_id,
  ADD COLUMN IF NOT EXISTS seller_id BIGINT UNSIGNED NULL AFTER seller_type,
  ADD COLUMN IF NOT EXISTS gst_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00 AFTER total_amount,
  ADD COLUMN IF NOT EXISTS gst_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00 AFTER gst_percent,
  ADD COLUMN IF NOT EXISTS payable_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00 AFTER gst_amount,
  ADD COLUMN IF NOT EXISTS payment_batch_id BIGINT UNSIGNED NULL AFTER payable_amount;
